services:
  - type: web
    name: EXPRE-GRA
    env: python
    buildCommand: |
      apt-get update && apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: gunicorn "app:crear_app()"


