services:
  - type: web
    name: EXPRE-GRA
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn main:app
    envVars:
      - key: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/graphviz/bin:/usr/local/graphviz/sbin
